### ISSUE TITLE
Any plans for vertical slabs?

### ISSUE THREAD

**Issue by LikelyNight** [chimericdream/minekea#48]

**Comment by chimericdream** [comment]
Vertical slabs is something I have definitely considered. That said, I am still trying to decide between adding them myself or looking into the possibility of adding compatibility with one of the many mods which already add this. It will mostly boil down to the level of effort. If it'll be relatively straightforward to make my slabs compatible with another mod, that will probably be the route I go. I will bump this up the list of future work to look into. I won't make any promises about exactly when I'll be able to add this functionality, but we'll see what happens.
