### ISSUE TITLE
Do not rely on an exact version of ARRP

### ISSUE THREAD

**Issue by SolidBlock-cn** [chimericdream/minekea#57]
In the `fabric.mod.json`, the mod should not rely on an exact ARRP version. It breaks the compatibility if I update to a newer ARRP.

**Comment by chimericdream** [comment]
Good call-out. I originally relied on `*` for the version, but needed to update after some bugs got fixed. I will change it to be "x or later".

**Comment by chimericdream** [comment]
Actually, I just double checked, and I depend on `>=0.6.2`, so it should work if you are on that version or later.

What version of Minekea, Minecraft, and ARRP do you have?
