### ISSUE TITLE
Bookshelfs dont enhance the Enchanting Table

### ISSUE THREAD

**Issue by xanthian** [chimericdream/minekea#63]
As title.

Put appropriate amount of bookshelves around the enchanting table, no level 30 enchant available.
Repeat process with vanilla bookshelf, level 30 enchant shown

**Comment by chimericdream** [comment]
Can you elaborate? I just tried in a test world, and everything seems to be working as expected. It's possible there is some mod compatibility issue I need to look at.

**Comment by xanthian** [comment]
seems I was unknowingly playing a 1.18 version.
works fine on 1.19 apologies.

**Comment by chimericdream** [comment]
No worries. It's good to know that this is happening on 1.18, so I will reopen this. I still support 1.18 for bug fixes, so I want to be sure this gets addressed.

Thanks!
