### ISSUE TITLE
My game won't start

### ISSUE THREAD

**Issue by GhoulGirlz** [chimericdream/minekea#66]
My game won't get past the loading screen. I put in both mods I needed and tried to start the game and it wouldn't start
I'm using Minecraft 1.19 Minekea 1.19 3.3.3 and arrp 0.6.4

**Comment by chimericdream** [comment]
Do you have Patchouli installed? I've been meaning to add a check that conditionally loads the configs for that, but at present, I believe Patchouli is a required dependency as well.

If you do have Patchouli, can you post a crash log? It's possible there is a conflict with some other mod (or simply a different bug that I haven't run into and need to address).
