### ISSUE TITLE
Glass jar content lost after chunk reload

### ISSUE THREAD

**Issue by Restorer37** [chimericdream/minekea#70]
**Glass jar content lost after chunk reload**

**To Reproduce**
1. place glass jar
2. add glass jar content
 - type of content in the jar do not affect the jar content lost. Anything that can put in the jar will be lost after 3)
3. everyone in the chunk log out
 - it have to be zero active player in certain area around the jar to cause jar content lost
 - if one player log out but another player stay present near the jar, jar content will stay when log back in again while another player still present. 
4. when log back in, content in glass jar don't display, cannot take added item out, breaking jar don't drop jar with content. Jar with content lost its content and become empty jar.

**Expected behavior**
Glass jar keep its content after chunk being reload

**Environment**
 * 1.17.1
 * Minekea version: 2.6.1
 * multiplayer server, apply to jar placed and content add by both creative and survival player, server with big modpack

**Comment by chimericdream** [comment]
Thanks for the bug report! Officially I don't support 1.17.x anymore, but I will take a look to see whether this would be an easy fix. Can you link me to the modpack in question?
