### ISSUE TITLE
Display case take item but item don't being display

### ISSUE THREAD

**Issue by Restorer37** [chimericdream/minekea#71]
**Describe the bug**
Display case take item from player hand but item don't being display

**To Reproduce**
1. Place display case
2. Right click with item in hand
3. Nothing show up in display case
5. Item can be get back by breaking the display case

**Expected behavior**
Item show up in display case when right click at display case

**Environment**
 * 1.17.1
* Minekea version: 2.6.1
* multiplayer server, big modpack

**Comment by chimericdream** [comment]
Thanks for the bug report! Officially I don't support 1.17.x anymore, but I will take a look to see whether this would be an easy fix. Can you link me to the modpack in question?
